Fix Terraform deployment workflow and update lock file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -91,12 +91,28 @@ jobs:
                   docker push "$APP_IMAGE"
                   docker push "$DATABASE_IMAGE"
 
-            # Initalize Terraform and ensure that the lockfile is up to date.
-            # This prevents the workflow from running if a change has been made
-            # to the Terraform configuration without updating the lockfile.
+            # Initalize the Terraform working directory and download provider plugins.
             - name: Terraform init
               working-directory: terraform
-              run: terraform init -lockfile=readonly
+              run: terraform init
+
+            # Verify the Terraform lock file and ensure that the lockfile is up to date.
+            # This prevents the workflow from running if a change has been made
+            # to the Terraform configuration without updating the lockfile.
+            - name: Verify Terraform lock file
+              run: |
+                  if ! git diff --exit-code -- terraform/.terraform.lock.hcl; then
+                  echo "::error::.terraform.lock.hcl is out of date."
+                  exit 1
+                  fi
+
+            # Plan the Terraform configuration.
+            - name: Terraform plan
+              working-directory: terraform
+              env:
+                  TF_VAR_app_image: ${{ env.APP_IMAGE }}
+                  TF_VAR_database_image: ${{ env.DATABASE_IMAGE }}
+              run: terraform plan -out=tfplan
 
             # Apply the Terraform configuration to the VPS.
             - name: Terraform apply
